spring.application.name=schedulling
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/espacoautoestima?useSSL=false
spring.datasource.username=root
spring.datasource.password=E$p@c02024!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# H2 Database Configuration (for testing)
# spring.datasource.url=jdbc:h2:mem:schedulling_db;DB_CLOSE_DELAY=-
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect


